#!/usr/bin/env bash

# This grabs data from a google spreadsheet and creates dict.local in the
# current working directory. Intended for use in ling113, spring 2015.

FILEKEY="1WwGgZxk5RoU0TAOoJlKPUsoEgZEYjEgucD7zrK3n6Xo"
GID="0"
DOC_URL="https://docs.google.com/feeds/download/spreadsheets/Export?key=${FILEKEY}&exportFormat=tsv&gid=${GID}"
OUTFILE="dict.local"

# We bail (-f) on error so as not to overwrite a valid cache
# NOTE: inplace editing (perl -i) does *not* work in a virtualbox
# shared folder on a Windows host, which is why a temporary file is used.
curl -f -L -o ${OUTFILE}.tmp ${DOC_URL}

if [ $? == 0 ]; then
  # Print first two columns iff they have word characters and first column
  # does not contain any whitespace.
  # Replace \t separator with two spaces.
  perl -n -e "if (/^[^\s]*\w[^\s]*\t[^\t]*\w/) { s/([^\t]+)\t([^\t]+).*/\1  \2/; print}" ${OUTFILE}.tmp > ${OUTFILE}
  if [ -f ${OUTFILE} ]; then
    rm ${OUTFILE}.tmp
  fi
  # Aligner requires a newline at the end of dict.local.
  echo "" >> ${OUTFILE}
else
  echo "Failed to retrieve data for dict.local."
  exit 1
fi

